### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by LiYaling-heb** [LWJ312/ION#3]
Thank you very much for your work. It is very helpful to me.
However, when I clicked this link to download the dataset, there was no response. Could you update it ?
Morever, the same thing happened to this link of [AI2THOR_Modified_Build] .

**Comment by LWJ312** [comment]
Sorry for the late reply. The download works fine if you copy the link and open it in a new tab in the browser.

**Comment by LiYaling-heb** [comment]
Thank you very much for your reply. I can download it！
